driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 4096

transport:
  name: winrm

provisioner:
  name: chef_zero

platforms:
  - name: win2012r2-chef11
    driver_config:
      box: chef/windows-server-2012r2-standard
    provisioner:
      require_chef_omnibus: 11.18.6
  - name: win2012r2-chef12
    driver_config:
      box: chef/windows-server-2012r2-standard
    provisioner:
      require_chef_omnibus: latest
  - name: win2008r2-chef11
    driver_config:
      box: chef/windows-server-2008r2-standard
    provisioner:
      require_chef_omnibus: 11.18.6
  - name: win2008r2-chef12
    driver_config:
      box: chef/windows-server-2008r2-standard
    provisioner:
      require_chef_omnibus: latest

suites:
  - name: default
    run_list:
      - recipe[iis::default]

